"use client";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.css";
import { Inter } from "next/font/google";
import React,{useEffect} from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  useEffect(() => {
    import("../../public/js/jquery.min.js");
    import("../../public/js/main.js");
    import("../../public/js/particles.min.js");
  }, []);
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}

        {/* <script src="./js/jquery.min.js"></script>
        <script src="./js/main.js"></script>
        <script src="./js/particles.min.js"></script> */}
      </body>
    </html>
  );
}
